version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    hostname: localhost
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  postgres-notes:
    hostname: localhost
    image: postgres
    environment:
      POSTGRES_DB: "notes"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
  postgres-users:
    hostname: localhost
    image: postgres
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
  users:
    hostname: localhost
    image: iampetrovpavel/users
    ports:
      - "3001:3001"
  notes:
    hostname: localhost
    image: iampetrovpavel/notes
    ports:
      - "3000:3000"
  mail:
    image: iampetrovpavel/mail
    ports:
      - "3002:3002"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local